locale: "da"
cdn: "http://cdn.pdl.bc/"
upload_path: "/web/uploads"
upload_path_gallery: "/web/gallery_images"
redis:
    dsn:
        schema:   "tcp"
        host:     "127.0.0.1"
        port:     6379
        database: 2
    options:
        profile:  "2.2"
        prefix:   "ishii:"
db:
    driver: "pdo_mysql"
    host: "127.0.0.1"
    dbname: "ishii"
    user: "root"
    password: "root"
facebook:
    default:
        app_id: 369414099809404
        secret: "1150097b7dbd7d0dcf806cea7931c9b5"
        page_id: 152545524804286
        page_url: "https://www.facebook.com/pages/Anders-Bryrup/152545524804286"